Repository willayy/modularml, pull requests merged in 2025-04, with the labels that each got.

#167 Fix Bug: Change bracket types in templates and police
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/invalid.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/issue_police.yaml
  .github/workflows/pr_police.yaml
Labels: bug, invalid

#173 Add Feature: Abstract DataLoader, DataLoaderConfig and concrete ImageLoader
  CMakeLists.txt
  Makefile
  src/backend/dataloader/image_loader.cpp
  src/include/backend/dataloader/a_data_loader.hpp
  src/include/backend/dataloader/data_loader_config.hpp
  src/include/backend/dataloader/image_loader.hpp
  tests/data/mnist_5.jpg
  tests/data/rgb_test.png
  tests/test_image_loader.cpp
Labels: enhancement

#172 Update Feature: Modularization of tensor operations and instantiation
  src/datastructures/array_utility.tpp
  src/datastructures/mml_array.tpp
  src/datastructures/mml_tensor.tpp
  src/datastructures/tensor_factory.tpp
  src/datastructures/tensor_factory_functions.tpp
  src/datastructures/tensor_operation_functions.tpp
  src/datastructures/tensor_operations_module.tpp
  src/datastructures/tensor_utility.tpp
  src/include/backend/a_arithmetic_module.hpp
  src/include/backend/a_gemm.hpp
  src/include/backend/a_onnx_gemm.hpp
  src/include/backend/mml_arithmetic.hpp
  src/include/backend/mml_gemm.hpp
  src/include/backend/mml_onnx_gemm.hpp
  src/include/datastructures/a_tensor.hpp
  src/include/datastructures/array_utility.hpp
  src/include/datastructures/mml_array.hpp
  src/include/datastructures/mml_tensor.hpp
  src/include/datastructures/tensor_factory.hpp
  src/include/datastructures/tensor_factory_functions.hpp
  src/include/datastructures/tensor_operation_functions.hpp
  src/include/datastructures/tensor_operations_module.hpp
  src/include/datastructures/tensor_utility.hpp
  src/include/globals.hpp
  src/include/modularml
  tests/test_tensor_operations_module.cpp
Labels: enhancement

#178 Add Feature: Lenet parser test
  .gitignore
  external/onnx2json/.github/workflows/codeql-analysis.yml
  external/onnx2json/.github/workflows/python-publish.yml
  external/onnx2json/.gitignore
  external/onnx2json/LICENSE
  external/onnx2json/README.md
  external/onnx2json/onnx2json/__init__.py
  external/onnx2json/onnx2json/__main__.py
  external/onnx2json/sample_models/NonMaxSuppression.onnx.zip
  external/onnx2json/setup.py
  lenet.json
  onnx2json.py
  onnx_to_json.py
  src/backend/mml_model.cpp
  src/backend/mml_parser.cpp
  src/datastructures/mml_tensor.tpp
  src/include/backend/parser_helper.hpp
  src/include/datastructures/a_tensor.hpp
  src/include/datastructures/mml_tensor.hpp
  src/include/nodes/add.hpp
  src/include/nodes/constant.hpp
  src/include/utility/base64.hpp
  src/nodes/avg_pooling.cpp
  src/nodes/constant.cpp
  src/nodes/conv.cpp
  src/nodes/dropout.cpp
  src/nodes/elu.cpp
  src/nodes/flatten.cpp
  src/nodes/gelu.cpp
  src/nodes/gemm.cpp
  src/nodes/leaky_relu.cpp
  src/nodes/log_softmax.cpp
  src/nodes/lrn.cpp
  src/nodes/max_pooling.cpp
  src/nodes/pooling.cpp
  src/nodes/reshape.cpp
  tests/test_mml_tensor.cpp
  tests/test_parser_model.cpp
Labels: enhancement

#176 Add Feature: Blocked GEMM, AVX, AVX512 & Compile specific GEMM implementations
  CMakeLists.txt
  Makefile
  README.md
  src/datastructures/mml_array.tpp
  src/datastructures/tensor_operation_functions.tpp
  src/datastructures/tensor_operations_module.tpp
  tests/test_mml_gemm.cpp
Labels: enhancement

#195 Fix Bug: With output tensor width and height
  src/backend/dataloader/image_loader.cpp
  tests/data/alps.JPEG
  tests/test_image_loader.cpp
Labels: bug

#197 Update Feature: Refactor broadcast and slicing
  CMakeLists.txt
  src/datastructures/mml_array.tpp
  src/datastructures/mml_tensor.tpp
  src/datastructures/tensor_operation_functions.tpp
  src/datastructures/tensor_operations_module.tpp
  src/datastructures/tensor_utility.tpp
  src/include/datastructures/a_tensor.hpp
  src/include/datastructures/mml_tensor.hpp
  src/include/datastructures/tensor_utility.hpp
  src/nodes/gemm.cpp
  tests/test_mml_tensor.cpp
Labels: enhancement

#205 Fix Invalid: remove deprecated methods and classes
  CMakeLists.txt
  src/backend/dataloader/image_loader.cpp
  src/backend/mml_arithmetic.tpp
  src/backend/mml_gemm.tpp
  src/backend/mml_normalizer.cpp
  src/backend/mml_onnx_gemm.tpp
  src/datastructures/mml_tensor.tpp
  src/datastructures/tensor_factory.tpp
  src/datastructures/tensor_operation_functions.tpp
  src/datastructures/tensor_operations_module.tpp
  src/datastructures/tensor_utility.tpp
  src/include/backend/a_arithmetic_module.hpp
  src/include/backend/a_gemm.hpp
  src/include/backend/a_onnx_gemm.hpp
  src/include/backend/mml_arithmetic.hpp
  src/include/backend/mml_gemm.hpp
  src/include/backend/mml_onnx_gemm.hpp
  src/include/backend/parser_helper.hpp
  src/include/datastructures/mml_tensor.hpp
  src/include/datastructures/tensor_operations_module.hpp
  src/include/datastructures/tensor_utility.hpp
  src/include/modularml
  src/include/nodes/a_node.hpp
  src/nodes/add.cpp
  src/nodes/avg_pool.cpp
  src/nodes/conv.cpp
  src/nodes/elu.cpp
  src/nodes/gelu.cpp
  src/nodes/gemm.cpp
  src/nodes/leaky_relu.cpp
  src/nodes/max_pool.cpp
  src/nodes/relu.cpp
  src/nodes/sigmoid.cpp
  src/nodes/swish.cpp
  src/nodes/tanh.cpp
  tests/test_activation_nodes.cpp
  tests/test_conv_node.cpp
  tests/test_flatten_node.cpp
  tests/test_gemm_node.cpp
  tests/test_image_to_guess.cpp
  tests/test_log_softmax_node.cpp
  tests/test_lrn_node.cpp
  tests/test_mml_arithmetic.cpp
  tests/test_mml_gemm.cpp
  tests/test_mml_onnx_gemm.cpp
  tests/test_mml_pooling.cpp
  tests/test_mml_tensor.cpp
  tests/test_normalizer.cpp
  tests/test_parser_model.cpp
  tests/test_reshape_node.cpp
  tests/test_tensor_operations_module.cpp
  tests/test_tensor_utility.cpp
Labels: invalid

#208 Add Feature: MatMul & Transpose Nodes
  src/backend/mml_parser.cpp
  src/datastructures/mml_array.tpp
  src/datastructures/mml_tensor.tpp
  src/include/datastructures/a_tensor.hpp
  src/include/datastructures/mml_tensor.hpp
  src/include/modularml
  src/include/nodes/matmul.hpp
  src/include/nodes/transpose.hpp
  src/nodes/matmul.cpp
  src/nodes/transpose.cpp
  tests/test_matmul_node.cpp
  tests/test_transpose_node.cpp
Labels: enhancement

#209 Fix Invalid: Fixed some of the linter warnings
  .github/workflows/clang_format.yaml
  .github/workflows/super_linter.yaml
  src/backend/dataloader/image_loader.cpp
  src/backend/dataloader/image_resizer_and_cropper.cpp
  src/backend/mml_parser.cpp
  src/datastructures/mml_array.tpp
  src/datastructures/mml_tensor.tpp
  src/datastructures/tensor_operation_functions.tpp
  src/datastructures/tensor_operations_module.tpp
  src/include/backend/dataloader/image_loader.hpp
  src/include/datastructures/a_tensor.hpp
  src/include/datastructures/mml_array.hpp
  src/include/datastructures/mml_tensor.hpp
  src/include/nodes/add.hpp
  src/include/nodes/avg_pool.hpp
  src/include/nodes/constant.hpp
  src/include/nodes/conv.hpp
  src/include/nodes/dropout.hpp
  src/include/nodes/elu.hpp
  src/include/nodes/flatten.hpp
  src/include/nodes/gelu.hpp
  src/include/nodes/gemm.hpp
  src/include/nodes/leaky_relu.hpp
  src/include/nodes/log_softmax.hpp
  src/include/nodes/lrn.hpp
  src/include/nodes/max_pool.hpp
  src/include/nodes/node_utils.hpp
  src/include/nodes/relu.hpp
  src/include/nodes/reshape.hpp
  src/include/nodes/sigmoid.hpp
  src/include/nodes/swish.hpp
  src/include/nodes/tanh.hpp
  src/include/utility/base64.hpp
  src/nodes/add.cpp
  src/nodes/avg_pool.cpp
  src/nodes/constant.cpp
  src/nodes/conv.cpp
  src/nodes/dropout.cpp
  src/nodes/elu.cpp
  src/nodes/flatten.cpp
  src/nodes/gelu.cpp
  src/nodes/gemm.cpp
  src/nodes/leaky_relu.cpp
  src/nodes/log_softmax.cpp
  src/nodes/lrn.cpp
  src/nodes/max_pool.cpp
  src/nodes/relu.cpp
  src/nodes/reshape.cpp
  src/nodes/sigmoid.cpp
  src/nodes/swish.cpp
  src/nodes/tanh.cpp
Labels: invalid
