Repository willayy/modularml, pull requests merged in 2025-03, with the labels that each got.

#108 Fix Invalid: Tensor assignment operation declaration
  src/include/a_tensor.hpp
  src/include/array_mml.hpp
  src/include/globals.hpp
  src/include/mml_tensor.hpp
  tests/test_mml_gemm.cpp
  tests/test_mml_tensor.cpp
  tests/test_nodes.cpp
Labels: invalid

#110 Update Feature: Make Tensor more abstract and split up implementation and definitions
  CMakeLists.txt
  src/include/a_elementwise.hpp
  src/include/a_tensor.hpp
  src/include/array_mml.hpp
  src/include/mml_tensor.hpp
  src/include/modularml
  src/mml_tensor.tpp
  src/placeholder.cpp
  tests/test_mml_tensor.cpp
Labels: enhancement

#120 Fix Invalid: Formula uses a different formula than onnx
  CMakeLists.txt
  src/include/a_onnx_gemm.hpp
  src/include/globals.hpp
  src/include/mml_gemm.hpp
  src/include/mml_onnx_gemm.hpp
  src/include/modularml
  src/mml_gemm.tpp
  src/mml_onnx_gemm.tpp
  tests/test_mml_gemm.cpp
  tests/test_mml_onnx_gemm.cpp
Labels: invalid

#126 Update Feature: Refactored all classes than can be slit up into hpp / tpp
  CMakeLists.txt
  Makefile
  src/ReLU_node.tpp
  src/Swish_node.tpp
  src/TanH_node.tpp
  src/array_mml.tpp
  src/gemm_node.tpp
  src/include/ReLU_node.hpp
  src/include/Swish_node.hpp
  src/include/TanH_node.hpp
  src/include/a_arithmetic_module.hpp
  src/include/array_mml.hpp
  src/include/gemm_node.hpp
  src/include/globals.hpp
  src/include/mml_arithmetic.hpp
  src/include/tensor_utility.hpp
  src/mml_arithmetic.tpp
  src/tensor_utility.tpp
  tests/test_nodes.cpp
Labels: enhancement

#121 Add Feature: Reshape node
  src/include/modularml
  src/include/reshape_node.hpp
  src/reshape_node.tpp
  tests/test_nodes.cpp
Labels: enhancement

#115 Add Feature: Conv Node
  Makefile
  src/conv_node.tpp
  src/include/conv_node.hpp
  tests/test_conv_node.cpp
Labels: enhancement

#130 124 Add onnx script functionality
  .gitmodules
  external/onnx2json/.github/workflows/codeql-analysis.yml
  external/onnx2json/.github/workflows/python-publish.yml
  external/onnx2json/.gitignore
  external/onnx2json/LICENSE
  external/onnx2json/README.md
  external/onnx2json/onnx2json/__init__.py
  external/onnx2json/onnx2json/__main__.py
  external/onnx2json/onnx2json/onnx2json.py
  external/onnx2json/sample_models/NonMaxSuppression.onnx.zip
  external/onnx2json/setup.py
  onnx_to_json.py
Labels: enhancement

#129 Add Feature: New workflow for uploading documentation to GH page
  .github/workflows/ci_cd.yaml
  .github/workflows/modularml-wiki
  .github/workflows/upload_documentation.yaml
  CMakeLists.txt
  Doxyfile
Labels: enhancement

#122 Add Feature: Dropout Node
  src/Dropout_node.tpp
  src/include/Dropout_node.hpp
  src/include/modularml
  src/include/tensor_utility.hpp
  src/tensor_utility.tpp
  tests/test_nodes.cpp
Labels: enhancement

#136 Add Feature: Flatten node
  src/flatten_node.tpp
  src/include/flatten_node.hpp
  src/include/modularml
  tests/test_flatten_node.cpp
Labels: enhancement

#141 Add Feature: MaxPoolingNode and AvgPoolingNode
  src/include/globals.hpp
  src/include/mml_avg_pooling_node.hpp
  src/include/mml_max_pooling_node.hpp
  src/include/mml_pooling_node.hpp
  src/include/modularml
  src/mml_avg_pooling_node.tpp
  src/mml_max_pooling_node.tpp
  src/mml_pooling_node.tpp
  tests/test_mml_pooling.cpp
Labels: enhancement

#146 Fix Bug: Getting incorrect parameters based on input and weight tensor
  src/conv_node.tpp
  src/include/conv_node.hpp
Labels: bug, enhancement

#142 Add Feature: add Node
  src/Add_node.tpp
  src/include/Add_node.hpp
  src/include/a_arithmetic_module.hpp
  src/include/mml_arithmetic.hpp
  src/include/modularml
  src/mml_arithmetic.tpp
  tests/test_Add_node.cpp
Labels: enhancement

#150 Add Feature: Timer utility
  src/include/profiler.hpp
  src/profiler.cpp
  tests/test_profiler.cpp
Labels: enhancement

#138 Add Feature: LogSoftMax Node
  src/include/log_softmax_node.hpp
  src/include/modularml
  src/log_softmax_node.tpp
  tests/test_log_softmax_node.cpp
Labels: enhancement

#159 Add Feature: Add node
  src/Add_node.tpp
  src/include/Add_node.hpp
  src/include/a_arithmetic_module.hpp
  src/include/mml_arithmetic.hpp
  src/include/modularml
  src/mml_arithmetic.tpp
  tests/test_Add_node.cpp
Labels: enhancement

#164 Add Feature: ArgMax function
  src/include/a_arithmetic_module.hpp
  src/include/mml_arithmetic.hpp
  src/mml_arithmetic.tpp
  tests/test_mml_arithmetic.cpp
Labels: enhancement

#166 Add Feature: Kaiming Uniform Distribution function
  src/include/tensor_utility.hpp
  src/tensor_utility.tpp
  tests/test_tensor_utility.cpp
Labels: enhancement

#168 Add Feature: Additions to README and workflows
  .github/workflows/ci_cd.yaml
  .github/workflows/upload_docs_coverage.yaml
  .github/workflows/upload_documentation.yaml
  CMakeLists.txt
  README.md
Labels: documentation
